name: Build and push packages '@hulog/core' and '@hulog/cli'

on:
  push:
    branches: master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Prepare deploy files
        run: |
          mkdir -p dist-core
          cp -r ./packages/core/dist dist-core/
          cp ./packages/core/package.json dist-core/
          mkdir -p dist-cli
          cp -r ./packages/cli/dist dist-cli/
          cp ./packages/cli/package.json dist-cli/

      - name: Deploy @hulog/core branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-core
          publish_branch: dist-core
          force_orphan: true

      - name: Deploy @hulog/cli branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-cli
          publish_branch: dist-cli
          force_orphan: true
